services:
  orbslam3:
    image: orbslam:latest
    container_name: adamas_orbslam3

    network_mode: host
    privileged: true

    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_LOCALHOST_ONLY=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/vision/tumvi/tumvi/calibrated/512_16:/dataset

    working_dir: /root/colcon_ws

    stdin_open: true
    tty: true

    command: >
      bash -c "
      export LD_LIBRARY_PATH=/root/ORB_SLAM3/lib:$LD_LIBRARY_PATH &&
      source /opt/ros/foxy/setup.bash &&
      source /root/colcon_ws/install/setup.bash &&
      ros2 run orbslam3 stereo-inertial /root/ORB_SLAM3/Vocabulary/ORBvoc.txt /root/colcon_ws/src/orbslam3_ros2/config/stereo-inertial/TUM-VI.yaml --ros-args -r /camera/left:=/cam0/image_raw -r /camera/right:=/cam1/image_raw -r /imu:=/imu0 "
